<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icons8-car-engine-64.ico</ApplicationIcon>
	  <FileVersion>1.0.0.0</FileVersion>
	  <InformationalVersion>1.0.0</InformationalVersion>
	  <Product>Gen3 MAF Tuning Tool</Product>
	  <Description>Tool for analyzing and generating LS Gen3 MAF curves</Description>
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
	  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icons8-car-engine-64.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.103">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

</Project>